apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    name: api-gateway
spec:
  ports:
    - port: 8050
      targetPort: 8050
      protocol: TCP
  selector:
    app: api-gateway
#  type: LoadBalancer
