
spring.cloud.gateway.discovery.locator.enabled: true
spring.cloud.gateway.discovery.locator.lower-case-service-id: true
management.endpoints.web.exposure.include: '*'
server.port: 8050
spring:
  cloud:
    gateway:
      routes:
        - id: bootdemo
          uri: http://bootdemo:8080/
          predicates:
            - Path=/api/bootdemo/**
        - id: discovery
          uri: http://discovery-client:8090/
          predicates:
            - Path=/api/discovery/**
        #   filters:
        #     - StripPrefix=1
